---
name: dotnet-bsp
description: Build Server for .NET C#
homepage: https://github.com/616b2f/dotnet-bsp
licenses:
  - MIT
languages:
  - C#
categories: []

source:
  # renovate:datasource=git-refs
  id: pkg:github/616b2f/dotnet-bsp@9f0e156ba56ff8eb09cf070769bba55e4e68aa57
  build:
    run: |
      dotnet build
      dotnet publish

bin:
  dotnet-bsp: dotnet:bin/dotnet-bsp.dll
