---
name: dotnet-bsp
description: Build Server for .NET C#
homepage: https://github.com/616b2f/dotnet-bsp
licenses:
  - MIT
languages:
  - C#
categories: []

source:
  # renovate:datasource=git-refs
  id: pkg:github/616b2f/dotnet-bsp@4b456c3441b645b0444a39cedc162787e64b2756
  build:
    run: |
      dotnet build
      dotnet publish

bin:
  dotnet-bsp: dotnet:bin/dotnet-bsp.dll
