---
name: dotnet-bsp
description: Build Server for .NET C#
homepage: https://github.com/616b2f/dotnet-bsp
licenses:
  - MIT
languages:
  - C#
categories: []

source:
  # renovate:datasource=git-refs
  id: pkg:github/616b2f/dotnet-bsp@309d170e951a4805182c998c512f034d7a63c5cc
  build:
    run: |
      dotnet build
      dotnet publish

bin:
  dotnet-bsp: dotnet:bin/dotnet-bsp.dll
