---
name: dotnet-bsp
description: Build Server for .NET C#
homepage: https://github.com/616b2f/dotnet-bsp
licenses:
  - MIT
languages:
  - C#
categories: []

source:
  # renovate:datasource=git-refs
  id: pkg:github/616b2f/dotnet-bsp@ef9116e18f4fba4d86cecb58168530fceba13cb0
  build:
    run: |
      dotnet build
      dotnet publish

bin:
  dotnet-bsp: dotnet:bin/dotnet-bsp.dll
