---
name: bazel-bsp
description: An implementation of the Build Server Protocol for Bazel
homepage: https://github.com/VirtusLab/bazel-bsp
licenses:
  - Apache-2.0
languages:
  - Java
  - Kotlin
  - Scala
  - Python
  - Thrift
  - Rust
categories: []

source:
  # renovate:datasource=github-releases
  id: pkg:generic/virtuslab/bazel-bsp@4.0.4
  download:
    files:
      bazel-bsp.jar: https://repo1.maven.org/maven2/org/virtuslab/bazel-bsp/{{ version | strip_prefix "v" }}/bazel-bsp-{{ version | strip_prefix "v" }}.jar

bin:
  bazel-bsp: java-jar:bazel-bsp.jar

share:
  bazel-bsp/bazel-bsp.jar: bazel-bsp.jar
