---
name: bazel-bsp
description: An implementation of the Build Server Protocol for Bazel
homepage: https://github.com/JetBrains/bazel-bsp
licenses:
  - Apache-2.0
languages:
  - Java
  - Kotlin
  - Scala
  - Python
  - Thrift
  - Rust
categories: []

source:
  id: pkg:github/JetBrains/bazel-bsp@3.2.0
  build:
    run: |
      bazel build //...

bin:
  bazel-bsp: java-jar:server/build/libs/server.jar

share:
  bazel-bsp/server.jar: server/build/libs/server.jar
  bazel-bsp/plugins/: server/build/libs/plugins/
  bazel-bsp/runtime/: server/build/libs/runtime/
