---
name: cargo-bsp
description: Build Server for cargo
homepage: https://github.com/616b2f/dotnet-bsp
licenses:
  - Apache-2.0
languages:
  - Rust
categories: []

source:
  # renovate:datasource=git-refs
  id: pkg:github.com/cargo-bsp/cargo-bsp@d7fa0a0e6db12bdc31daf0be7dd6280e9ecc3442
  build:
    run: |
      cargo build

bin:
  cargo-bsp: target/release/server
